name: Security check - Bandit

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
    name: Python ${{ matrix.os }} 

    steps:
    - uses: actions/checkout@v2

    - name: Environment
      run: |
        bash -c set

    - name: Run bandit
      uses: ioggstream/bandit-report-artifacts@v0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        project_path: redis_ipc.py
        ignore_failure: true
